/**
 * Pictogramas de la agenda visual de PT y AL y de las fichas con apoyos
 * visuales: una selección de Mulberry Symbols, de Steve Lee, con licencia
 * Creative Commons
 * Reconocimiento-CompartirIgual 4.0 (CC BY-SA 4.0), que permite el uso
 * comercial. Van dentro de la aplicación, en `public/pictos/mulberry/`, sin
 * modificar (solo optimizados con svgo), con su licencia al lado: funcionan
 * sin conexión y no se envía nada. La atribución tiene que verse en
 * Configuración y al pie de cada agenda o ficha impresa que los lleve
 * (`ATRIBUCION_MULBERRY`). Los que empiezan por `ap-` son dibujos propios de
 * AulaPro para las consignas de ficha que Mulberry no tiene (rodear, unir,
 * subrayar…), en `public/pictos/aulapro/`: no piden atribución.
 * ARASAAC, Sclera y Soy Visual no se pueden usar: su licencia no permite el
 * uso comercial. Ver `docs/PTAL.md`.
 *
 * Archivo generado por `scripts/pictos/generar.py` con la lista de
 * `scripts/pictos/lista.py`: no se cambia a mano.
 */
import type { Lang } from '../i18n';

export type CategoriaPicto =
  | 'rutinas'
  | 'clase'
  | 'material'
  | 'acciones'
  | 'consignas'
  | 'emociones'
  | 'personas'
  | 'comida'
  | 'lugares'
  | 'juego'
  | 'tiempo'
  | 'matematicas'
  | 'naturaleza'
  | 'cuerpo'
  | 'transporte';

export interface Picto { id: string; categoria: CategoriaPicto; es: string; ca: string; en: string }

export const CATEGORIAS_PICTO: readonly { id: CategoriaPicto; es: string; ca: string; en: string }[] = [
  { id: 'rutinas', es: 'Rutinas', ca: 'Rutines', en: 'Routines' },
  { id: 'clase', es: 'En clase', ca: 'A classe', en: 'In class' },
  { id: 'material', es: 'Material', ca: 'Material', en: 'Materials' },
  { id: 'acciones', es: 'Acciones', ca: 'Accions', en: 'Actions' },
  { id: 'consignas', es: 'Consignas de ficha', ca: 'Consignes de fitxa', en: 'Worksheet instructions' },
  { id: 'emociones', es: 'Cómo me siento', ca: 'Com em sento', en: 'Feelings' },
  { id: 'personas', es: 'Personas', ca: 'Persones', en: 'People' },
  { id: 'comida', es: 'Comida', ca: 'Menjar', en: 'Food' },
  { id: 'lugares', es: 'Lugares', ca: 'Llocs', en: 'Places' },
  { id: 'juego', es: 'Juego', ca: 'Joc', en: 'Play' },
  { id: 'tiempo', es: 'Cuándo', ca: 'Quan', en: 'When' },
  { id: 'matematicas', es: 'Matemáticas', ca: 'Matemàtiques', en: 'Maths' },
  { id: 'naturaleza', es: 'Naturaleza', ca: 'Natura', en: 'Nature' },
  { id: 'cuerpo', es: 'El cuerpo', ca: 'El cos', en: 'The body' },
  { id: 'transporte', es: 'Transporte', ca: 'Transport', en: 'Transport' },
];

export const PICTOS: readonly Picto[] = [
  { id: 'ap-rodear', categoria: 'consignas', es: 'Rodear', ca: 'Encerclar', en: 'Circle' },
  { id: 'ap-unir', categoria: 'consignas', es: 'Unir con una línea', ca: 'Unir amb una línia', en: 'Match with a line' },
  { id: 'ap-subrayar', categoria: 'consignas', es: 'Subrayar', ca: 'Subratllar', en: 'Underline' },
  { id: 'ap-tachar', categoria: 'consignas', es: 'Tachar', ca: 'Ratllar', en: 'Cross out' },
  { id: 'ap-marcar', categoria: 'consignas', es: 'Marcar', ca: 'Marcar', en: 'Tick' },
  { id: 'ap-completar', categoria: 'consignas', es: 'Completar', ca: 'Completar', en: 'Fill in the gap' },
  { id: 'ap-ordenar', categoria: 'consignas', es: 'Ordenar', ca: 'Ordenar', en: 'Put in order' },
  { id: 'ap-elegir', categoria: 'consignas', es: 'Elegir la respuesta', ca: 'Triar la resposta', en: 'Choose the answer' },
  { id: 'ap-verdadero-falso', categoria: 'consignas', es: 'Verdadero o falso', ca: 'Vertader o fals', en: 'True or false' },
  { id: 'ap-sopa-letras', categoria: 'consignas', es: 'Buscar palabras', ca: 'Buscar paraules', en: 'Word search' },
  { id: 'ap-palotes', categoria: 'consignas', es: 'Hacer palotes', ca: 'Fer palets', en: 'Tally marks' },
  { id: 'ap-tabla', categoria: 'consignas', es: 'Rellenar la tabla', ca: 'Omplir la taula', en: 'Fill in the table' },
  { id: 'ap-regla', categoria: 'consignas', es: 'Medir con la regla', ca: 'Mesurar amb el regle', en: 'Measure with a ruler' },
  { id: 'eye', categoria: 'consignas', es: 'Observar', ca: 'Observar', en: 'Look carefully' },
  { id: 'hear', categoria: 'consignas', es: 'Escuchar', ca: 'Escoltar', en: 'Listen' },
  { id: 'point', categoria: 'consignas', es: 'Señalar', ca: 'Assenyalar', en: 'Point' },
  { id: 'colour', categoria: 'consignas', es: 'Colorear', ca: 'Pintar de colors', en: 'Colour in' },
  { id: 'glue', categoria: 'consignas', es: 'Pegar', ca: 'Enganxar', en: 'Glue' },
  { id: 'tape-measure', categoria: 'consignas', es: 'Medir', ca: 'Mesurar', en: 'Measure' },
  { id: 'weigh', categoria: 'consignas', es: 'Pesar', ca: 'Pesar', en: 'Weigh' },
  { id: 'show-me', categoria: 'consignas', es: 'Enseñar', ca: 'Ensenyar', en: 'Show' },
  { id: 'hello', categoria: 'rutinas', es: 'Hola', ca: 'Hola', en: 'Hello' },
  { id: 'hang-coat', categoria: 'rutinas', es: 'Colgar el abrigo', ca: 'Penjar l\'abric', en: 'Hang up your coat' },
  { id: 'put-on-coat', categoria: 'rutinas', es: 'Ponerse el abrigo', ca: 'Posar-se l\'abric', en: 'Put on your coat' },
  { id: 'wash-hands', categoria: 'rutinas', es: 'Lavarse las manos', ca: 'Rentar-se les mans', en: 'Wash your hands' },
  { id: 'dry-hands', categoria: 'rutinas', es: 'Secarse las manos', ca: 'Eixugar-se les mans', en: 'Dry your hands' },
  { id: 'toilet-go', categoria: 'rutinas', es: 'Ir al baño', ca: 'Anar al lavabo', en: 'Go to the toilet' },
  { id: 'need-toilet', categoria: 'rutinas', es: 'Necesito ir al baño', ca: 'Necessito anar al lavabo', en: 'I need the toilet' },
  { id: 'brush-teeth', categoria: 'rutinas', es: 'Lavarse los dientes', ca: 'Rentar-se les dents', en: 'Brush your teeth' },
  { id: 'get-dressed', categoria: 'rutinas', es: 'Vestirse', ca: 'Vestir-se', en: 'Get dressed' },
  { id: 'undress', categoria: 'rutinas', es: 'Desvestirse', ca: 'Desvestir-se', en: 'Get undressed' },
  { id: 'breakfast-time', categoria: 'rutinas', es: 'Desayuno', ca: 'Esmorzar', en: 'Breakfast' },
  { id: 'lunch-time', categoria: 'rutinas', es: 'Comida', ca: 'Dinar', en: 'Lunch' },
  { id: 'break-time-1', categoria: 'rutinas', es: 'Almuerzo del recreo', ca: 'Esmorzar del pati', en: 'Snack time' },
  { id: 'break-time-2', categoria: 'rutinas', es: 'Recreo', ca: 'Pati', en: 'Break time' },
  { id: 'tidy-2', categoria: 'rutinas', es: 'Recoger', ca: 'Endreçar', en: 'Tidy up' },
  { id: 'put-away', categoria: 'rutinas', es: 'Guardar', ca: 'Desar', en: 'Put away' },
  { id: 'queue', categoria: 'rutinas', es: 'Hacer la fila', ca: 'Fer la fila', en: 'Line up' },
  { id: 'wait', categoria: 'rutinas', es: 'Esperar', ca: 'Esperar', en: 'Wait' },
  { id: 'sit', categoria: 'rutinas', es: 'Sentarse', ca: 'Seure', en: 'Sit down' },
  { id: 'stand', categoria: 'rutinas', es: 'Ponerse de pie', ca: 'Posar-se dret', en: 'Stand up' },
  { id: 'get-on-bus', categoria: 'rutinas', es: 'Subir al autobús', ca: 'Pujar a l\'autobús', en: 'Get on the bus' },
  { id: 'get-off-bus', categoria: 'rutinas', es: 'Bajar del autobús', ca: 'Baixar de l\'autobús', en: 'Get off the bus' },
  { id: 'school-bag', categoria: 'rutinas', es: 'Mochila', ca: 'Motxilla', en: 'School bag' },
  { id: 'rest', categoria: 'rutinas', es: 'Descansar', ca: 'Descansar', en: 'Rest' },
  { id: 'begin-start', categoria: 'rutinas', es: 'Empezar', ca: 'Començar', en: 'Start' },
  { id: 'finish', categoria: 'rutinas', es: 'Terminar', ca: 'Acabar', en: 'Finish' },
  { id: 'time-out', categoria: 'rutinas', es: 'Tiempo fuera', ca: 'Temps fora', en: 'Time out' },
  { id: 'house', categoria: 'rutinas', es: 'Casa', ca: 'Casa', en: 'Home' },
  { id: 'school', categoria: 'clase', es: 'Colegio', ca: 'Escola', en: 'School' },
  { id: 'class-room', categoria: 'clase', es: 'Clase', ca: 'Classe', en: 'Classroom' },
  { id: 'circle-time', categoria: 'clase', es: 'Asamblea', ca: 'Assemblea', en: 'Circle time' },
  { id: 'maths-class', categoria: 'clase', es: 'Matemáticas', ca: 'Matemàtiques', en: 'Maths' },
  { id: 'english-class', categoria: 'clase', es: 'Lengua', ca: 'Llengua', en: 'Language' },
  { id: 'music-class', categoria: 'clase', es: 'Música', ca: 'Música', en: 'Music' },
  { id: 'pe-class', categoria: 'clase', es: 'Educación Física', ca: 'Educació Física', en: 'PE' },
  { id: 'art-class', categoria: 'clase', es: 'Plástica', ca: 'Plàstica', en: 'Art' },
  { id: 'science-class', categoria: 'clase', es: 'Ciencias', ca: 'Ciències', en: 'Science' },
  { id: 'it-class', categoria: 'clase', es: 'Informática', ca: 'Informàtica', en: 'Computing' },
  { id: 'swimming-class', categoria: 'clase', es: 'Natación', ca: 'Natació', en: 'Swimming' },
  { id: 'history-class', categoria: 'clase', es: 'Historia', ca: 'Història', en: 'History' },
  { id: 'geography-class', categoria: 'clase', es: 'Geografía', ca: 'Geografia', en: 'Geography' },
  { id: 'drama-class', categoria: 'clase', es: 'Teatro', ca: 'Teatre', en: 'Drama' },
  { id: 'group-work', categoria: 'clase', es: 'Trabajo en grupo', ca: 'Treball en grup', en: 'Group work' },
  { id: 'test', categoria: 'clase', es: 'Examen', ca: 'Examen', en: 'Test' },
  { id: 'worksheet', categoria: 'clase', es: 'Ficha', ca: 'Fitxa', en: 'Worksheet' },
  { id: 'work-book', categoria: 'clase', es: 'Cuaderno de trabajo', ca: 'Quadern de treball', en: 'Workbook' },
  { id: 'whiteboard', categoria: 'clase', es: 'Pizarra', ca: 'Pissarra', en: 'Whiteboard' },
  { id: 'no-class', categoria: 'clase', es: 'No hay clase', ca: 'No hi ha classe', en: 'No class' },
  { id: 'pencil', categoria: 'material', es: 'Lápiz', ca: 'Llapis', en: 'Pencil' },
  { id: 'pen', categoria: 'material', es: 'Bolígrafo', ca: 'Bolígraf', en: 'Pen' },
  { id: 'crayon', categoria: 'material', es: 'Cera', ca: 'Cera', en: 'Crayon' },
  { id: 'felt-tips', categoria: 'material', es: 'Rotuladores', ca: 'Retoladors', en: 'Felt tips' },
  { id: 'glue-stick', categoria: 'material', es: 'Pegamento', ca: 'Cola de barra', en: 'Glue stick' },
  { id: 'scissors', categoria: 'material', es: 'Tijeras', ca: 'Tisores', en: 'Scissors' },
  { id: 'paper', categoria: 'material', es: 'Papel', ca: 'Paper', en: 'Paper' },
  { id: 'notebook', categoria: 'material', es: 'Libreta', ca: 'Llibreta', en: 'Notebook' },
  { id: 'pencil-case', categoria: 'material', es: 'Estuche', ca: 'Estoig', en: 'Pencil case' },
  { id: 'pencil-sharpener', categoria: 'material', es: 'Sacapuntas', ca: 'Maquineta', en: 'Pencil sharpener' },
  { id: 'paint-brush', categoria: 'material', es: 'Pincel', ca: 'Pinzell', en: 'Paintbrush' },
  { id: 'calculator', categoria: 'material', es: 'Calculadora', ca: 'Calculadora', en: 'Calculator' },
  { id: 'dictionary', categoria: 'material', es: 'Diccionario', ca: 'Diccionari', en: 'Dictionary' },
  { id: 'computer-1', categoria: 'material', es: 'Ordenador', ca: 'Ordinador', en: 'Computer' },
  { id: 'laptop', categoria: 'material', es: 'Portátil', ca: 'Portàtil', en: 'Laptop' },
  { id: 'touch-screen', categoria: 'material', es: 'Pantalla táctil', ca: 'Pantalla tàctil', en: 'Touch screen' },
  { id: 'headphones', categoria: 'material', es: 'Auriculares', ca: 'Auriculars', en: 'Headphones' },
  { id: 'colouring-book', categoria: 'material', es: 'Libro para colorear', ca: 'Llibre per pintar', en: 'Colouring book' },
  { id: 'stickers', categoria: 'material', es: 'Pegatinas', ca: 'Adhesius', en: 'Stickers' },
  { id: 'clock', categoria: 'material', es: 'Reloj', ca: 'Rellotge', en: 'Clock' },
  { id: 'timer-2', categoria: 'material', es: 'Temporizador', ca: 'Temporitzador', en: 'Timer' },
  { id: 'communication-book', categoria: 'material', es: 'Libro de comunicación', ca: 'Llibre de comunicació', en: 'Communication book' },
  { id: 'read-book', categoria: 'acciones', es: 'Leer', ca: 'Llegir', en: 'Read' },
  { id: 'write', categoria: 'acciones', es: 'Escribir', ca: 'Escriure', en: 'Write' },
  { id: 'draw', categoria: 'acciones', es: 'Dibujar', ca: 'Dibuixar', en: 'Draw' },
  { id: 'paint', categoria: 'acciones', es: 'Pintar', ca: 'Pintar', en: 'Paint' },
  { id: 'count', categoria: 'acciones', es: 'Contar', ca: 'Comptar', en: 'Count' },
  { id: 'cut-with-scissors', categoria: 'acciones', es: 'Recortar', ca: 'Retallar', en: 'Cut out' },
  { id: 'cut-and-paste', categoria: 'acciones', es: 'Recortar y pegar', ca: 'Retallar i enganxar', en: 'Cut and paste' },
  { id: 'trace', categoria: 'acciones', es: 'Repasar', ca: 'Resseguir', en: 'Trace' },
  { id: 'copy', categoria: 'acciones', es: 'Copiar', ca: 'Copiar', en: 'Copy' },
  { id: 'spell', categoria: 'acciones', es: 'Deletrear', ca: 'Lletrejar', en: 'Spell' },
  { id: 'study', categoria: 'acciones', es: 'Estudiar', ca: 'Estudiar', en: 'Study' },
  { id: 'talk-1', categoria: 'acciones', es: 'Hablar', ca: 'Parlar', en: 'Talk' },
  { id: 'ask', categoria: 'acciones', es: 'Preguntar', ca: 'Preguntar', en: 'Ask' },
  { id: 'look', categoria: 'acciones', es: 'Mirar', ca: 'Mirar', en: 'Look' },
  { id: 'watch', categoria: 'acciones', es: 'Ver', ca: 'Veure', en: 'Watch' },
  { id: 'think', categoria: 'acciones', es: 'Pensar', ca: 'Pensar', en: 'Think' },
  { id: 'play', categoria: 'acciones', es: 'Jugar', ca: 'Jugar', en: 'Play' },
  { id: 'sing', categoria: 'acciones', es: 'Cantar', ca: 'Cantar', en: 'Sing' },
  { id: 'dance', categoria: 'acciones', es: 'Bailar', ca: 'Ballar', en: 'Dance' },
  { id: 'jump', categoria: 'acciones', es: 'Saltar', ca: 'Saltar', en: 'Jump' },
  { id: 'run', categoria: 'acciones', es: 'Correr', ca: 'Córrer', en: 'Run' },
  { id: 'walk', categoria: 'acciones', es: 'Caminar', ca: 'Caminar', en: 'Walk' },
  { id: 'exercise', categoria: 'acciones', es: 'Hacer ejercicio', ca: 'Fer exercici', en: 'Exercise' },
  { id: 'stretch', categoria: 'acciones', es: 'Estirarse', ca: 'Estirar-se', en: 'Stretch' },
  { id: 'swim', categoria: 'acciones', es: 'Nadar', ca: 'Nedar', en: 'Swim' },
  { id: 'kick-ball', categoria: 'acciones', es: 'Chutar', ca: 'Xutar', en: 'Kick' },
  { id: 'catch', categoria: 'acciones', es: 'Atrapar', ca: 'Atrapar', en: 'Catch' },
  { id: 'help', categoria: 'acciones', es: 'Ayudar', ca: 'Ajudar', en: 'Help' },
  { id: 'share', categoria: 'acciones', es: 'Compartir', ca: 'Compartir', en: 'Share' },
  { id: 'sort', categoria: 'acciones', es: 'Clasificar', ca: 'Classificar', en: 'Sort' },
  { id: 'build', categoria: 'acciones', es: 'Construir', ca: 'Construir', en: 'Build' },
  { id: 'clap-hands', categoria: 'acciones', es: 'Aplaudir', ca: 'Aplaudir', en: 'Clap' },
  { id: 'hold-hands', categoria: 'acciones', es: 'Darse la mano', ca: 'Donar-se la mà', en: 'Hold hands' },
  { id: 'open', categoria: 'acciones', es: 'Abrir', ca: 'Obrir', en: 'Open' },
  { id: 'close', categoria: 'acciones', es: 'Cerrar', ca: 'Tancar', en: 'Close' },
  { id: 'give', categoria: 'acciones', es: 'Dar', ca: 'Donar', en: 'Give' },
  { id: 'take', categoria: 'acciones', es: 'Coger', ca: 'Agafar', en: 'Take' },
  { id: 'find', categoria: 'acciones', es: 'Buscar', ca: 'Buscar', en: 'Find' },
  { id: 'want', categoria: 'acciones', es: 'Querer', ca: 'Voler', en: 'Want' },
  { id: 'eat', categoria: 'acciones', es: 'Comer', ca: 'Menjar', en: 'Eat' },
  { id: 'drink-2', categoria: 'acciones', es: 'Beber', ca: 'Beure', en: 'Drink' },
  { id: 'chew', categoria: 'acciones', es: 'Masticar', ca: 'Mastegar', en: 'Chew' },
  { id: 'blow', categoria: 'acciones', es: 'Soplar', ca: 'Bufar', en: 'Blow' },
  { id: 'smile', categoria: 'acciones', es: 'Sonreír', ca: 'Somriure', en: 'Smile' },
  { id: 'whisper', categoria: 'acciones', es: 'Hablar bajito', ca: 'Parlar fluixet', en: 'Whisper' },
  { id: 'shout', categoria: 'acciones', es: 'Gritar', ca: 'Cridar', en: 'Shout' },
  { id: 'relax', categoria: 'acciones', es: 'Relajarse', ca: 'Relaxar-se', en: 'Relax' },
  { id: 'sleep-male', categoria: 'acciones', es: 'Dormir', ca: 'Dormir', en: 'Sleep' },
  { id: 'use-computer', categoria: 'acciones', es: 'Usar el ordenador', ca: 'Fer servir l\'ordinador', en: 'Use the computer' },
  { id: 'type', categoria: 'acciones', es: 'Teclear', ca: 'Teclejar', en: 'Type' },
  { id: 'happy-man', categoria: 'emociones', es: 'Contento', ca: 'Content', en: 'Happy' },
  { id: 'happy-lady', categoria: 'emociones', es: 'Contenta', ca: 'Contenta', en: 'Happy' },
  { id: 'sad-man', categoria: 'emociones', es: 'Triste', ca: 'Trist', en: 'Sad' },
  { id: 'sad-lady', categoria: 'emociones', es: 'Triste', ca: 'Trista', en: 'Sad' },
  { id: 'angry-man', categoria: 'emociones', es: 'Enfadado', ca: 'Enfadat', en: 'Angry' },
  { id: 'angry-lady', categoria: 'emociones', es: 'Enfadada', ca: 'Enfadada', en: 'Angry' },
  { id: 'afraid-man', categoria: 'emociones', es: 'Con miedo', ca: 'Amb por', en: 'Scared' },
  { id: 'afraid-lady', categoria: 'emociones', es: 'Con miedo', ca: 'Amb por', en: 'Scared' },
  { id: 'surprised-man', categoria: 'emociones', es: 'Sorprendido', ca: 'Sorprès', en: 'Surprised' },
  { id: 'surprised-lady', categoria: 'emociones', es: 'Sorprendida', ca: 'Sorpresa', en: 'Surprised' },
  { id: 'worried-man', categoria: 'emociones', es: 'Preocupado', ca: 'Preocupat', en: 'Worried' },
  { id: 'worried-lady', categoria: 'emociones', es: 'Preocupada', ca: 'Preocupada', en: 'Worried' },
  { id: 'serene-man', categoria: 'emociones', es: 'Tranquilo', ca: 'Tranquil', en: 'Calm' },
  { id: 'serene-lady', categoria: 'emociones', es: 'Tranquila', ca: 'Tranquil·la', en: 'Calm' },
  { id: 'excited-man', categoria: 'emociones', es: 'Emocionado', ca: 'Emocionat', en: 'Excited' },
  { id: 'excited-lady', categoria: 'emociones', es: 'Emocionada', ca: 'Emocionada', en: 'Excited' },
  { id: 'confused-man', categoria: 'emociones', es: 'Confundido', ca: 'Confós', en: 'Confused' },
  { id: 'confused-lady', categoria: 'emociones', es: 'Confundida', ca: 'Confosa', en: 'Confused' },
  { id: 'concentrating-man', categoria: 'emociones', es: 'Concentrado', ca: 'Concentrat', en: 'Concentrating' },
  { id: 'concentrating-lady', categoria: 'emociones', es: 'Concentrada', ca: 'Concentrada', en: 'Concentrating' },
  { id: 'hungry', categoria: 'emociones', es: 'Tengo hambre', ca: 'Tinc gana', en: 'Hungry' },
  { id: 'thirsty', categoria: 'emociones', es: 'Tengo sed', ca: 'Tinc set', en: 'Thirsty' },
  { id: 'good', categoria: 'emociones', es: 'Bien', ca: 'Bé', en: 'Good' },
  { id: 'bad', categoria: 'emociones', es: 'Mal', ca: 'Malament', en: 'Bad' },
  { id: 'correct', categoria: 'emociones', es: 'Correcto', ca: 'Correcte', en: 'Correct' },
  { id: 'mistake-no-wrong', categoria: 'emociones', es: 'Incorrecto', ca: 'Incorrecte', en: 'Wrong' },
  { id: 'more', categoria: 'emociones', es: 'Más', ca: 'Més', en: 'More' },
  { id: 'quiet', categoria: 'emociones', es: 'Silencio', ca: 'Silenci', en: 'Quiet' },
  { id: 'teacher-1a', categoria: 'personas', es: 'Maestro', ca: 'Mestre', en: 'Teacher' },
  { id: 'teacher-2a', categoria: 'personas', es: 'Maestra', ca: 'Mestra', en: 'Teacher' },
  { id: 'teacher-1b', categoria: 'personas', es: 'Maestro', ca: 'Mestre', en: 'Teacher' },
  { id: 'teacher-2b', categoria: 'personas', es: 'Maestra', ca: 'Mestra', en: 'Teacher' },
  { id: 'head-teacher-1a', categoria: 'personas', es: 'Director', ca: 'Director', en: 'Head teacher' },
  { id: 'head-teacher-2a', categoria: 'personas', es: 'Directora', ca: 'Directora', en: 'Head teacher' },
  { id: 'speech-language-therapist-1a', categoria: 'personas', es: 'Logopeda', ca: 'Logopeda', en: 'Speech therapist' },
  { id: 'speech-language-therapist-2a', categoria: 'personas', es: 'Logopeda', ca: 'Logopeda', en: 'Speech therapist' },
  { id: 'physio-therapist-1a', categoria: 'personas', es: 'Fisioterapeuta', ca: 'Fisioterapeuta', en: 'Physiotherapist' },
  { id: 'occupational-therapist-1a', categoria: 'personas', es: 'Terapeuta ocupacional', ca: 'Terapeuta ocupacional', en: 'Occupational therapist' },
  { id: 'care-assistant-1a', categoria: 'personas', es: 'Educador', ca: 'Educador', en: 'Support assistant' },
  { id: 'care-assistant-2a', categoria: 'personas', es: 'Educadora', ca: 'Educadora', en: 'Support assistant' },
  { id: 'nurse-1a', categoria: 'personas', es: 'Enfermero', ca: 'Infermer', en: 'Nurse' },
  { id: 'nurse-2a', categoria: 'personas', es: 'Enfermera', ca: 'Infermera', en: 'Nurse' },
  { id: 'doctor-1a', categoria: 'personas', es: 'Médico', ca: 'Metge', en: 'Doctor' },
  { id: 'doctor-2a', categoria: 'personas', es: 'Médica', ca: 'Metgessa', en: 'Doctor' },
  { id: 'cook-school-1a', categoria: 'personas', es: 'Cocinero', ca: 'Cuiner', en: 'Cook' },
  { id: 'family', categoria: 'personas', es: 'Familia', ca: 'Família', en: 'Family' },
  { id: 'mum-parent', categoria: 'personas', es: 'Mamá', ca: 'Mama', en: 'Mum' },
  { id: 'dad-parent', categoria: 'personas', es: 'Papá', ca: 'Papa', en: 'Dad' },
  { id: 'brother', categoria: 'personas', es: 'Hermano', ca: 'Germà', en: 'Brother' },
  { id: 'sister', categoria: 'personas', es: 'Hermana', ca: 'Germana', en: 'Sister' },
  { id: 'grandmother', categoria: 'personas', es: 'Abuela', ca: 'Àvia', en: 'Grandmother' },
  { id: 'grandfather', categoria: 'personas', es: 'Abuelo', ca: 'Avi', en: 'Grandfather' },
  { id: 'water', categoria: 'comida', es: 'Agua', ca: 'Aigua', en: 'Water' },
  { id: 'milk', categoria: 'comida', es: 'Leche', ca: 'Llet', en: 'Milk' },
  { id: 'orange-juice', categoria: 'comida', es: 'Zumo', ca: 'Suc', en: 'Juice' },
  { id: 'sandwich', categoria: 'comida', es: 'Bocadillo', ca: 'Entrepà', en: 'Sandwich' },
  { id: 'bread', categoria: 'comida', es: 'Pan', ca: 'Pa', en: 'Bread' },
  { id: 'fruit', categoria: 'comida', es: 'Fruta', ca: 'Fruita', en: 'Fruit' },
  { id: 'apple', categoria: 'comida', es: 'Manzana', ca: 'Poma', en: 'Apple' },
  { id: 'banana', categoria: 'comida', es: 'Plátano', ca: 'Plàtan', en: 'Banana' },
  { id: 'orange', categoria: 'comida', es: 'Naranja', ca: 'Taronja', en: 'Orange' },
  { id: 'yogurt', categoria: 'comida', es: 'Yogur', ca: 'Iogurt', en: 'Yoghurt' },
  { id: 'biscuits', categoria: 'comida', es: 'Galletas', ca: 'Galetes', en: 'Biscuits' },
  { id: 'soup', categoria: 'comida', es: 'Sopa', ca: 'Sopa', en: 'Soup' },
  { id: 'pizza', categoria: 'comida', es: 'Pizza', ca: 'Pizza', en: 'Pizza' },
  { id: 'spoon', categoria: 'comida', es: 'Cuchara', ca: 'Cullera', en: 'Spoon' },
  { id: 'fork', categoria: 'comida', es: 'Tenedor', ca: 'Forquilla', en: 'Fork' },
  { id: 'plate', categoria: 'comida', es: 'Plato', ca: 'Plat', en: 'Plate' },
  { id: 'glass-drinking', categoria: 'comida', es: 'Vaso', ca: 'Got', en: 'Glass' },
  { id: 'lunch-box', categoria: 'comida', es: 'Fiambrera', ca: 'Carmanyola', en: 'Lunch box' },
  { id: 'pear', categoria: 'comida', es: 'Pera', ca: 'Pera', en: 'Pear' },
  { id: 'grapes', categoria: 'comida', es: 'Uvas', ca: 'Raïm', en: 'Grapes' },
  { id: 'strawberry', categoria: 'comida', es: 'Fresa', ca: 'Maduixa', en: 'Strawberry' },
  { id: 'carrot', categoria: 'comida', es: 'Zanahoria', ca: 'Pastanaga', en: 'Carrot' },
  { id: 'tomato', categoria: 'comida', es: 'Tomate', ca: 'Tomàquet', en: 'Tomato' },
  { id: 'potato', categoria: 'comida', es: 'Patata', ca: 'Patata', en: 'Potato' },
  { id: 'egg', categoria: 'comida', es: 'Huevo', ca: 'Ou', en: 'Egg' },
  { id: 'cheese', categoria: 'comida', es: 'Queso', ca: 'Formatge', en: 'Cheese' },
  { id: 'cake', categoria: 'comida', es: 'Pastel', ca: 'Pastís', en: 'Cake' },
  { id: 'chocolate', categoria: 'comida', es: 'Chocolate', ca: 'Xocolata', en: 'Chocolate' },
  { id: 'rice', categoria: 'comida', es: 'Arroz', ca: 'Arròs', en: 'Rice' },
  { id: 'pasta', categoria: 'comida', es: 'Pasta', ca: 'Pasta', en: 'Pasta' },
  { id: 'play-area', categoria: 'lugares', es: 'Parque', ca: 'Parc', en: 'Play area' },
  { id: 'toilets', categoria: 'lugares', es: 'Baño', ca: 'Lavabo', en: 'Toilets' },
  { id: 'sensory-room', categoria: 'lugares', es: 'Sala sensorial', ca: 'Sala sensorial', en: 'Sensory room' },
  { id: 'music-room', categoria: 'lugares', es: 'Aula de música', ca: 'Aula de música', en: 'Music room' },
  { id: 'art-room', categoria: 'lugares', es: 'Aula de plástica', ca: 'Aula de plàstica', en: 'Art room' },
  { id: 'it-room', categoria: 'lugares', es: 'Aula de informática', ca: 'Aula d\'informàtica', en: 'Computer room' },
  { id: 'science-room', categoria: 'lugares', es: 'Laboratorio', ca: 'Laboratori', en: 'Science room' },
  { id: 'gym-1', categoria: 'lugares', es: 'Gimnasio', ca: 'Gimnàs', en: 'Gym' },
  { id: 'swing', categoria: 'lugares', es: 'Columpio', ca: 'Gronxador', en: 'Swing' },
  { id: 'slide', categoria: 'lugares', es: 'Tobogán', ca: 'Tobogan', en: 'Slide' },
  { id: 'door', categoria: 'lugares', es: 'Puerta', ca: 'Porta', en: 'Door' },
  { id: 'bus-single-decker', categoria: 'lugares', es: 'Autobús', ca: 'Autobús', en: 'Bus' },
  { id: 'car', categoria: 'lugares', es: 'Coche', ca: 'Cotxe', en: 'Car' },
  { id: 'wheelchair', categoria: 'lugares', es: 'Silla de ruedas', ca: 'Cadira de rodes', en: 'Wheelchair' },
  { id: 'surgery-health-centre', categoria: 'lugares', es: 'Centro de salud', ca: 'Centre de salut', en: 'Health centre' },
  { id: 'beach', categoria: 'lugares', es: 'Playa', ca: 'Platja', en: 'Beach' },
  { id: 'ball', categoria: 'juego', es: 'Pelota', ca: 'Pilota', en: 'Ball' },
  { id: 'bricks', categoria: 'juego', es: 'Bloques', ca: 'Blocs', en: 'Bricks' },
  { id: 'lego', categoria: 'juego', es: 'Piezas de construcción', ca: 'Peces de construcció', en: 'Building blocks' },
  { id: 'jigsaw-puzzle', categoria: 'juego', es: 'Puzle', ca: 'Trencaclosques', en: 'Jigsaw' },
  { id: 'toys', categoria: 'juego', es: 'Juguetes', ca: 'Joguines', en: 'Toys' },
  { id: 'bubbles', categoria: 'juego', es: 'Pompas', ca: 'Bombolles', en: 'Bubbles' },
  { id: 'puppet', categoria: 'juego', es: 'Marioneta', ca: 'Titella', en: 'Puppet' },
  { id: 'teddy-bear', categoria: 'juego', es: 'Peluche', ca: 'Ninot de peluix', en: 'Teddy bear' },
  { id: 'doll', categoria: 'juego', es: 'Muñeca', ca: 'Nina', en: 'Doll' },
  { id: 'toy-car', categoria: 'juego', es: 'Coche de juguete', ca: 'Cotxe de joguina', en: 'Toy car' },
  { id: 'dinosaur', categoria: 'juego', es: 'Dinosaurio', ca: 'Dinosaure', en: 'Dinosaur' },
  { id: 'playing-cards', categoria: 'juego', es: 'Cartas', ca: 'Cartes', en: 'Cards' },
  { id: 'roll-dice', categoria: 'juego', es: 'Tirar el dado', ca: 'Tirar el dau', en: 'Roll the dice' },
  { id: 'computer-game', categoria: 'juego', es: 'Videojuego', ca: 'Videojoc', en: 'Computer game' },
  { id: 'musical-instruments', categoria: 'juego', es: 'Instrumentos', ca: 'Instruments', en: 'Instruments' },
  { id: 'drum', categoria: 'juego', es: 'Tambor', ca: 'Tambor', en: 'Drum' },
  { id: 'beanbag', categoria: 'juego', es: 'Puf', ca: 'Puf', en: 'Beanbag' },
  { id: 'trampoline', categoria: 'juego', es: 'Cama elástica', ca: 'Llit elàstic', en: 'Trampoline' },
  { id: 'childrens-tv', categoria: 'juego', es: 'Dibujos animados', ca: 'Dibuixos animats', en: 'Cartoons' },
  { id: 'morning', categoria: 'tiempo', es: 'Por la mañana', ca: 'Al matí', en: 'Morning' },
  { id: 'afternoon', categoria: 'tiempo', es: 'Por la tarde', ca: 'A la tarda', en: 'Afternoon' },
  { id: 'night', categoria: 'tiempo', es: 'Noche', ca: 'Nit', en: 'Night' },
  { id: 'today', categoria: 'tiempo', es: 'Hoy', ca: 'Avui', en: 'Today' },
  { id: 'tomorrow', categoria: 'tiempo', es: 'Mañana', ca: 'Demà', en: 'Tomorrow' },
  { id: 'yesterday', categoria: 'tiempo', es: 'Ayer', ca: 'Ahir', en: 'Yesterday' },
  { id: 'now', categoria: 'tiempo', es: 'Ahora', ca: 'Ara', en: 'Now' },
  { id: 'first', categoria: 'tiempo', es: 'Primero', ca: 'Primer', en: 'First' },
  { id: 'next', categoria: 'tiempo', es: 'Siguiente', ca: 'Següent', en: 'Next' },
  { id: 'last', categoria: 'tiempo', es: 'Último', ca: 'Últim', en: 'Last' },
  { id: 'before', categoria: 'tiempo', es: 'Antes', ca: 'Abans', en: 'Before' },
  { id: 'after', categoria: 'tiempo', es: 'Después', ca: 'Després', en: 'After' },
  { id: 'calendar', categoria: 'tiempo', es: 'Calendario', ca: 'Calendari', en: 'Calendar' },
  { id: 'sun', categoria: 'tiempo', es: 'Sol', ca: 'Sol', en: 'Sun' },
  { id: 'cloudy', categoria: 'tiempo', es: 'Nublado', ca: 'Ennuvolat', en: 'Cloudy' },
  { id: 'rain', categoria: 'tiempo', es: 'Lluvia', ca: 'Pluja', en: 'Rain' },
  { id: 'snow', categoria: 'tiempo', es: 'Nieve', ca: 'Neu', en: 'Snow' },
  { id: 'ap-sumar', categoria: 'matematicas', es: 'Sumar', ca: 'Sumar', en: 'Add' },
  { id: 'subtract', categoria: 'matematicas', es: 'Restar', ca: 'Restar', en: 'Subtract' },
  { id: 'multiply', categoria: 'matematicas', es: 'Multiplicar', ca: 'Multiplicar', en: 'Multiply' },
  { id: 'divide', categoria: 'matematicas', es: 'Dividir', ca: 'Dividir', en: 'Divide' },
  { id: 'same', categoria: 'matematicas', es: 'Igual', ca: 'Igual', en: 'Equal' },
  { id: 'count-2', categoria: 'matematicas', es: 'Números', ca: 'Nombres', en: 'Numbers' },
  { id: 'counters', categoria: 'matematicas', es: 'Fichas para contar', ca: 'Fitxes per comptar', en: 'Counters' },
  { id: 'half', categoria: 'matematicas', es: 'La mitad', ca: 'La meitat', en: 'Half' },
  { id: 'money', categoria: 'matematicas', es: 'Dinero', ca: 'Diners', en: 'Money' },
  { id: 'square', categoria: 'matematicas', es: 'Cuadrado', ca: 'Quadrat', en: 'Square' },
  { id: 'rectangle', categoria: 'matematicas', es: 'Rectángulo', ca: 'Rectangle', en: 'Rectangle' },
  { id: 'triangle-equilateral', categoria: 'matematicas', es: 'Triángulo', ca: 'Triangle', en: 'Triangle' },
  { id: 'circle', categoria: 'matematicas', es: 'Círculo', ca: 'Cercle', en: 'Circle' },
  { id: 'oval', categoria: 'matematicas', es: 'Óvalo', ca: 'Oval', en: 'Oval' },
  { id: 'pyramid-square-base', categoria: 'matematicas', es: 'Pirámide', ca: 'Piràmide', en: 'Pyramid' },
  { id: 'shapes', categoria: 'matematicas', es: 'Figuras', ca: 'Figures', en: 'Shapes' },
  { id: 'measuring-jug', categoria: 'matematicas', es: 'Jarra medidora', ca: 'Gerra mesuradora', en: 'Measuring jug' },
  { id: 'scales', categoria: 'matematicas', es: 'Báscula de cocina', ca: 'Bàscula de cuina', en: 'Kitchen scales' },
  { id: 'scales-2', categoria: 'matematicas', es: 'Báscula', ca: 'Bàscula', en: 'Scales' },
  { id: 'graph-column', categoria: 'matematicas', es: 'Gráfico de barras', ca: 'Gràfic de barres', en: 'Bar chart' },
  { id: 'pie-chart', categoria: 'matematicas', es: 'Gráfico de sectores', ca: 'Gràfic de sectors', en: 'Pie chart' },
  { id: 'long', categoria: 'matematicas', es: 'Largo', ca: 'Llarg', en: 'Long' },
  { id: 'short', categoria: 'matematicas', es: 'Bajo', ca: 'Baix', en: 'Short' },
  { id: 'heavy', categoria: 'matematicas', es: 'Pesado', ca: 'Pesant', en: 'Heavy' },
  { id: 'full', categoria: 'matematicas', es: 'Lleno', ca: 'Ple', en: 'Full' },
  { id: 'empty', categoria: 'matematicas', es: 'Vacío', ca: 'Buit', en: 'Empty' },
  { id: 'minute', categoria: 'matematicas', es: 'Minuto', ca: 'Minut', en: 'Minute' },
  { id: 'dog', categoria: 'naturaleza', es: 'Perro', ca: 'Gos', en: 'Dog' },
  { id: 'cat', categoria: 'naturaleza', es: 'Gato', ca: 'Gat', en: 'Cat' },
  { id: 'bird', categoria: 'naturaleza', es: 'Pájaro', ca: 'Ocell', en: 'Bird' },
  { id: 'fish', categoria: 'naturaleza', es: 'Pez', ca: 'Peix', en: 'Fish' },
  { id: 'horse', categoria: 'naturaleza', es: 'Caballo', ca: 'Cavall', en: 'Horse' },
  { id: 'cow', categoria: 'naturaleza', es: 'Vaca', ca: 'Vaca', en: 'Cow' },
  { id: 'piglet', categoria: 'naturaleza', es: 'Cerdo', ca: 'Porc', en: 'Pig' },
  { id: 'sheep', categoria: 'naturaleza', es: 'Oveja', ca: 'Ovella', en: 'Sheep' },
  { id: 'rabbit', categoria: 'naturaleza', es: 'Conejo', ca: 'Conill', en: 'Rabbit' },
  { id: 'duck', categoria: 'naturaleza', es: 'Pato', ca: 'Ànec', en: 'Duck' },
  { id: 'frog', categoria: 'naturaleza', es: 'Rana', ca: 'Granota', en: 'Frog' },
  { id: 'butterfly', categoria: 'naturaleza', es: 'Mariposa', ca: 'Papallona', en: 'Butterfly' },
  { id: 'bee-bumble', categoria: 'naturaleza', es: 'Abeja', ca: 'Abella', en: 'Bee' },
  { id: 'lion', categoria: 'naturaleza', es: 'León', ca: 'Lleó', en: 'Lion' },
  { id: 'elephant', categoria: 'naturaleza', es: 'Elefante', ca: 'Elefant', en: 'Elephant' },
  { id: 'tree', categoria: 'naturaleza', es: 'Árbol', ca: 'Arbre', en: 'Tree' },
  { id: 'flower', categoria: 'naturaleza', es: 'Flor', ca: 'Flor', en: 'Flower' },
  { id: 'leaf', categoria: 'naturaleza', es: 'Hoja', ca: 'Fulla', en: 'Leaf' },
  { id: 'plant', categoria: 'naturaleza', es: 'Planta', ca: 'Planta', en: 'Plant' },
  { id: 'mountains', categoria: 'naturaleza', es: 'Montaña', ca: 'Muntanya', en: 'Mountain' },
  { id: 'moon', categoria: 'naturaleza', es: 'Luna', ca: 'Lluna', en: 'Moon' },
  { id: 'star', categoria: 'naturaleza', es: 'Estrella', ca: 'Estel', en: 'Star' },
  { id: 'rainbow', categoria: 'naturaleza', es: 'Arcoíris', ca: 'Arc de Sant Martí', en: 'Rainbow' },
  { id: 'head', categoria: 'cuerpo', es: 'Cabeza', ca: 'Cap', en: 'Head' },
  { id: 'eyes', categoria: 'cuerpo', es: 'Ojos', ca: 'Ulls', en: 'Eyes' },
  { id: 'ear', categoria: 'cuerpo', es: 'Oreja', ca: 'Orella', en: 'Ear' },
  { id: 'mouth', categoria: 'cuerpo', es: 'Boca', ca: 'Boca', en: 'Mouth' },
  { id: 'teeth', categoria: 'cuerpo', es: 'Dientes', ca: 'Dents', en: 'Teeth' },
  { id: 'arm', categoria: 'cuerpo', es: 'Brazo', ca: 'Braç', en: 'Arm' },
  { id: 'leg', categoria: 'cuerpo', es: 'Pierna', ca: 'Cama', en: 'Leg' },
  { id: 'foot', categoria: 'cuerpo', es: 'Pie', ca: 'Peu', en: 'Foot' },
  { id: 'finger', categoria: 'cuerpo', es: 'Dedo', ca: 'Dit', en: 'Finger' },
  { id: 'train', categoria: 'transporte', es: 'Tren', ca: 'Tren', en: 'Train' },
  { id: 'boat', categoria: 'transporte', es: 'Barco', ca: 'Vaixell', en: 'Boat' },
  { id: 'bicycle', categoria: 'transporte', es: 'Bicicleta', ca: 'Bicicleta', en: 'Bicycle' },
];

export { ATRIBUCION_MULBERRY } from './atribucionPictos';

/** ¿Es de Mulberry? Los propios de AulaPro (`ap-`) no piden atribución. */
export function esMulberry(id: string): boolean {
  return !id.startsWith('ap-');
}

/** Dónde está el dibujo, relativo a la página (la app se carga con `base: './'`). */
export function urlPicto(id: string): string {
  return esMulberry(id)
    ? `${import.meta.env.BASE_URL}pictos/mulberry/${id}.svg`
    : `${import.meta.env.BASE_URL}pictos/aulapro/${id.slice(3)}.svg`;
}

export function pictoDe(id: string): Picto | undefined {
  return PICTOS.find(p => p.id === id);
}

export function nombrePicto(p: Picto | { es: string; ca: string; en: string }, lang: Lang): string {
  return p[lang];
}

/** Para buscar sin tildes ni mayúsculas, en el idioma de la app y en castellano. */
const plano = (s: string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

export function buscarPictos(texto: string, lang: Lang, categoria?: CategoriaPicto): Picto[] {
  const t = plano(texto.trim());
  return PICTOS.filter(p => (!categoria || p.categoria === categoria)
    && (!t || plano(p[lang]).includes(t) || plano(p.es).includes(t)));
}
