# Pictogramas de la agenda visual de PT y AL y de las fichas con apoyos
# visuales. Por categoría: (nombre del archivo en Mulberry, castellano,
# català, inglés). Los que empiezan por «@» son dibujos propios de AulaPro
# (`propios/`), para las consignas de ficha que Mulberry no tiene: rodear,
# unir, subrayar, tachar… Fuera los que llevan palabras en inglés dibujadas
# (semana, fin de semana, tablero de comunicación) y `plane`, que es un
# cepillo de carpintero y no un avión.
L = {
 'consignas': [
  ('@rodear','Rodear','Encerclar','Circle'),
  ('@unir','Unir con una línea','Unir amb una línia','Match with a line'),
  ('@subrayar','Subrayar','Subratllar','Underline'),
  ('@tachar','Tachar','Ratllar','Cross out'),
  ('@marcar','Marcar','Marcar','Tick'),
  ('@completar','Completar','Completar','Fill in the gap'),
  ('@ordenar','Ordenar','Ordenar','Put in order'),
  ('@elegir','Elegir la respuesta','Triar la resposta','Choose the answer'),
  ('@verdadero-falso','Verdadero o falso','Vertader o fals','True or false'),
  ('@sopa-letras','Buscar palabras','Buscar paraules','Word search'),
  ('@palotes','Hacer palotes','Fer palets','Tally marks'),
  ('@tabla','Rellenar la tabla','Omplir la taula','Fill in the table'),
  ('@regla','Medir con la regla','Mesurar amb el regle','Measure with a ruler'),
  ('eye','Observar','Observar','Look carefully'),
  ('hear_,_to','Escuchar','Escoltar','Listen'),
  ('point_,_to','Señalar','Assenyalar','Point'),
  ('colour','Colorear','Pintar de colors','Colour in'),
  ('glue','Pegar','Enganxar','Glue'),
  ('tape_measure','Medir','Mesurar','Measure'),
  ('weigh_,_to','Pesar','Pesar','Weigh'),
  ('show_me_,_to','Enseñar','Ensenyar','Show'),
 ],
 'rutinas': [
  ('hello','Hola','Hola','Hello'),
  ('hang_coat_,_to','Colgar el abrigo','Penjar l\'abric','Hang up your coat'),
  ('put_on_coat_,_to','Ponerse el abrigo','Posar-se l\'abric','Put on your coat'),
  ('wash_hands_,_to','Lavarse las manos','Rentar-se les mans','Wash your hands'),
  ('dry_hands_,_to','Secarse las manos','Eixugar-se les mans','Dry your hands'),
  ('toilet_,_go_to_the','Ir al baño','Anar al lavabo','Go to the toilet'),
  ('need_toilet','Necesito ir al baño','Necessito anar al lavabo','I need the toilet'),
  ('brush_teeth_,_to','Lavarse los dientes','Rentar-se les dents','Brush your teeth'),
  ('get_dressed_,_to','Vestirse','Vestir-se','Get dressed'),
  ('undress_,_to','Desvestirse','Desvestir-se','Get undressed'),
  ('breakfast_time','Desayuno','Esmorzar','Breakfast'),
  ('lunch_time','Comida','Dinar','Lunch'),
  ('break_time_1','Almuerzo del recreo','Esmorzar del pati','Snack time'),
  ('break_time_2','Recreo','Pati','Break time'),
  ('tidy_2_,_to','Recoger','Endreçar','Tidy up'),
  ('put_away_,_to','Guardar','Desar','Put away'),
  ('queue_,_to','Hacer la fila','Fer la fila','Line up'),
  ('wait_,_to','Esperar','Esperar','Wait'),
  ('sit_,_to','Sentarse','Seure','Sit down'),
  ('stand_,_to','Ponerse de pie','Posar-se dret','Stand up'),
  ('get_on_bus_,_to','Subir al autobús','Pujar a l\'autobús','Get on the bus'),
  ('get_off_bus_,_to','Bajar del autobús','Baixar de l\'autobús','Get off the bus'),
  ('school_bag','Mochila','Motxilla','School bag'),
  ('rest_,_to','Descansar','Descansar','Rest'),
  ('begin_start','Empezar','Començar','Start'),
  ('finish','Terminar','Acabar','Finish'),
  ('time_out','Tiempo fuera','Temps fora','Time out'),
  ('house','Casa','Casa','Home'),
 ],
 'clase': [
  ('school','Colegio','Escola','School'),
  ('class_room','Clase','Classe','Classroom'),
  ('circle_time','Asamblea','Assemblea','Circle time'),
  ('maths_class','Matemáticas','Matemàtiques','Maths'),
  ('english_class','Lengua','Llengua','Language'),
  ('music_class','Música','Música','Music'),
  ('PE_class','Educación Física','Educació Física','PE'),
  ('art_class','Plástica','Plàstica','Art'),
  ('science_class','Ciencias','Ciències','Science'),
  ('IT_class','Informática','Informàtica','Computing'),
  ('swimming_class','Natación','Natació','Swimming'),
  ('history_class','Historia','Història','History'),
  ('geography_class','Geografía','Geografia','Geography'),
  ('drama_class','Teatro','Teatre','Drama'),
  ('group_work','Trabajo en grupo','Treball en grup','Group work'),
  ('test','Examen','Examen','Test'),
  ('worksheet','Ficha','Fitxa','Worksheet'),
  ('work_book','Cuaderno de trabajo','Quadern de treball','Workbook'),
  ('whiteboard','Pizarra','Pissarra','Whiteboard'),
  ('no_class','No hay clase','No hi ha classe','No class'),
 ],
 'material': [
  ('pencil','Lápiz','Llapis','Pencil'),
  ('pen','Bolígrafo','Bolígraf','Pen'),
  ('crayon','Cera','Cera','Crayon'),
  ('felt_tips','Rotuladores','Retoladors','Felt tips'),
  ('glue_stick','Pegamento','Cola de barra','Glue stick'),
  ('scissors','Tijeras','Tisores','Scissors'),
  ('paper','Papel','Paper','Paper'),
  ('notebook','Libreta','Llibreta','Notebook'),
  ('pencil_case','Estuche','Estoig','Pencil case'),
  ('pencil_sharpener','Sacapuntas','Maquineta','Pencil sharpener'),
  ('paint_brush','Pincel','Pinzell','Paintbrush'),
  ('calculator','Calculadora','Calculadora','Calculator'),
  ('dictionary','Diccionario','Diccionari','Dictionary'),
  ('computer_1','Ordenador','Ordinador','Computer'),
  ('laptop','Portátil','Portàtil','Laptop'),
  ('touch_screen','Pantalla táctil','Pantalla tàctil','Touch screen'),
  ('headphones','Auriculares','Auriculars','Headphones'),
  ('colouring_book','Libro para colorear','Llibre per pintar','Colouring book'),
  ('stickers','Pegatinas','Adhesius','Stickers'),
  ('clock','Reloj','Rellotge','Clock'),
  ('timer_2','Temporizador','Temporitzador','Timer'),
  ('communication_book','Libro de comunicación','Llibre de comunicació','Communication book'),
 ],
 'acciones': [
  ('read_book_,_to','Leer','Llegir','Read'),
  ('write_,_to','Escribir','Escriure','Write'),
  ('draw_,_to','Dibujar','Dibuixar','Draw'),
  ('paint_,_to','Pintar','Pintar','Paint'),
  ('count_,_to','Contar','Comptar','Count'),
  ('cut_with_scissors_,_to','Recortar','Retallar','Cut out'),
  ('cut_and_paste','Recortar y pegar','Retallar i enganxar','Cut and paste'),
  ('trace_,_to','Repasar','Resseguir','Trace'),
  ('copy_,_to','Copiar','Copiar','Copy'),
  ('spell_,_to','Deletrear','Lletrejar','Spell'),
  ('study_,_to','Estudiar','Estudiar','Study'),
  ('talk_1_,_to','Hablar','Parlar','Talk'),
  ('ask_,_to','Preguntar','Preguntar','Ask'),
  ('look_,_to','Mirar','Mirar','Look'),
  ('watch_,_to','Ver','Veure','Watch'),
  ('think_,_to','Pensar','Pensar','Think'),
  ('play_,_to','Jugar','Jugar','Play'),
  ('sing_,_to','Cantar','Cantar','Sing'),
  ('dance_,_to','Bailar','Ballar','Dance'),
  ('jump_,_to','Saltar','Saltar','Jump'),
  ('run_,_to','Correr','Córrer','Run'),
  ('walk_,_to','Caminar','Caminar','Walk'),
  ('exercise_,_to','Hacer ejercicio','Fer exercici','Exercise'),
  ('stretch_,_to','Estirarse','Estirar-se','Stretch'),
  ('swim_,_to','Nadar','Nedar','Swim'),
  ('kick_ball_,_to','Chutar','Xutar','Kick'),
  ('catch_,_to','Atrapar','Atrapar','Catch'),
  ('help_,_to','Ayudar','Ajudar','Help'),
  ('share_,_to','Compartir','Compartir','Share'),
  ('sort_,_to','Clasificar','Classificar','Sort'),
  ('build_,_to','Construir','Construir','Build'),
  ('clap_hands_,_to','Aplaudir','Aplaudir','Clap'),
  ('hold_hands_,_to','Darse la mano','Donar-se la mà','Hold hands'),
  ('open_,_to','Abrir','Obrir','Open'),
  ('close_,_to','Cerrar','Tancar','Close'),
  ('give_,_to','Dar','Donar','Give'),
  ('take_,_to','Coger','Agafar','Take'),
  ('find_,_to','Buscar','Buscar','Find'),
  ('want_,_to','Querer','Voler','Want'),
  ('eat_,_to','Comer','Menjar','Eat'),
  ('drink_2_,_to','Beber','Beure','Drink'),
  ('chew_,_to','Masticar','Mastegar','Chew'),
  ('blow_,_to','Soplar','Bufar','Blow'),
  ('smile_,_to','Sonreír','Somriure','Smile'),
  ('whisper_,_to','Hablar bajito','Parlar fluixet','Whisper'),
  ('shout_,_to','Gritar','Cridar','Shout'),
  ('relax_,_to','Relajarse','Relaxar-se','Relax'),
  ('sleep_male_,_to','Dormir','Dormir','Sleep'),
  ('use_computer_,_to','Usar el ordenador','Fer servir l\'ordinador','Use the computer'),
  ('type_,_to','Teclear','Teclejar','Type'),
 ],
 'emociones': [
  ('happy_man','Contento','Content','Happy'),
  ('happy_lady','Contenta','Contenta','Happy'),
  ('sad_man','Triste','Trist','Sad'),
  ('sad_lady','Triste','Trista','Sad'),
  ('angry_man','Enfadado','Enfadat','Angry'),
  ('angry_lady','Enfadada','Enfadada','Angry'),
  ('afraid_man','Con miedo','Amb por','Scared'),
  ('afraid_lady','Con miedo','Amb por','Scared'),
  ('surprised_man','Sorprendido','Sorprès','Surprised'),
  ('surprised_lady','Sorprendida','Sorpresa','Surprised'),
  ('worried_man','Preocupado','Preocupat','Worried'),
  ('worried_lady','Preocupada','Preocupada','Worried'),
  ('serene_man','Tranquilo','Tranquil','Calm'),
  ('serene_lady','Tranquila','Tranquil·la','Calm'),
  ('excited_man','Emocionado','Emocionat','Excited'),
  ('excited_lady','Emocionada','Emocionada','Excited'),
  ('confused_man','Confundido','Confós','Confused'),
  ('confused_lady','Confundida','Confosa','Confused'),
  ('concentrating_man','Concentrado','Concentrat','Concentrating'),
  ('concentrating_lady','Concentrada','Concentrada','Concentrating'),
  ('hungry','Tengo hambre','Tinc gana','Hungry'),
  ('thirsty','Tengo sed','Tinc set','Thirsty'),
  ('good','Bien','Bé','Good'),
  ('bad','Mal','Malament','Bad'),
  ('correct','Correcto','Correcte','Correct'),
  ('mistake_no_wrong','Incorrecto','Incorrecte','Wrong'),
  ('more','Más','Més','More'),
  ('quiet','Silencio','Silenci','Quiet'),
 ],
 'personas': [
  ('teacher_1a','Maestro','Mestre','Teacher'),
  ('teacher_2a','Maestra','Mestra','Teacher'),
  ('teacher_1b','Maestro','Mestre','Teacher'),
  ('teacher_2b','Maestra','Mestra','Teacher'),
  ('head_teacher_1a','Director','Director','Head teacher'),
  ('head_teacher_2a','Directora','Directora','Head teacher'),
  ('speech_language_therapist_1a','Logopeda','Logopeda','Speech therapist'),
  ('speech_language_therapist_2a','Logopeda','Logopeda','Speech therapist'),
  ('physio_therapist_1a','Fisioterapeuta','Fisioterapeuta','Physiotherapist'),
  ('occupational_therapist_1a','Terapeuta ocupacional','Terapeuta ocupacional','Occupational therapist'),
  ('care_assistant_1a','Educador','Educador','Support assistant'),
  ('care_assistant_2a','Educadora','Educadora','Support assistant'),
  ('nurse_1a','Enfermero','Infermer','Nurse'),
  ('nurse_2a','Enfermera','Infermera','Nurse'),
  ('doctor_1a','Médico','Metge','Doctor'),
  ('doctor_2a','Médica','Metgessa','Doctor'),
  ('cook_school_1a','Cocinero','Cuiner','Cook'),
  ('family','Familia','Família','Family'),
  ('mum_parent','Mamá','Mama','Mum'),
  ('dad_parent','Papá','Papa','Dad'),
  ('brother','Hermano','Germà','Brother'),
  ('sister','Hermana','Germana','Sister'),
  ('grandmother','Abuela','Àvia','Grandmother'),
  ('grandfather','Abuelo','Avi','Grandfather'),
 ],
 'comida': [
  ('water','Agua','Aigua','Water'),
  ('milk','Leche','Llet','Milk'),
  ('orange_juice','Zumo','Suc','Juice'),
  ('sandwich','Bocadillo','Entrepà','Sandwich'),
  ('bread','Pan','Pa','Bread'),
  ('fruit','Fruta','Fruita','Fruit'),
  ('apple','Manzana','Poma','Apple'),
  ('banana','Plátano','Plàtan','Banana'),
  ('orange','Naranja','Taronja','Orange'),
  ('yogurt','Yogur','Iogurt','Yoghurt'),
  ('biscuits','Galletas','Galetes','Biscuits'),
  ('soup','Sopa','Sopa','Soup'),
  ('pizza','Pizza','Pizza','Pizza'),
  ('spoon','Cuchara','Cullera','Spoon'),
  ('fork','Tenedor','Forquilla','Fork'),
  ('plate','Plato','Plat','Plate'),
  ('glass_,_drinking','Vaso','Got','Glass'),
  ('lunch_box','Fiambrera','Carmanyola','Lunch box'),
  ('pear','Pera','Pera','Pear'),
  ('grapes','Uvas','Raïm','Grapes'),
  ('strawberry','Fresa','Maduixa','Strawberry'),
  ('carrot','Zanahoria','Pastanaga','Carrot'),
  ('tomato','Tomate','Tomàquet','Tomato'),
  ('potato','Patata','Patata','Potato'),
  ('egg','Huevo','Ou','Egg'),
  ('cheese','Queso','Formatge','Cheese'),
  ('cake','Pastel','Pastís','Cake'),
  ('chocolate','Chocolate','Xocolata','Chocolate'),
  ('rice','Arroz','Arròs','Rice'),
  ('pasta','Pasta','Pasta','Pasta'),
 ],
 'lugares': [
  ('play_area','Parque','Parc','Play area'),
  ('toilets','Baño','Lavabo','Toilets'),
  ('sensory_room','Sala sensorial','Sala sensorial','Sensory room'),
  ('music_room','Aula de música','Aula de música','Music room'),
  ('art_room','Aula de plástica','Aula de plàstica','Art room'),
  ('IT_room','Aula de informática','Aula d\'informàtica','Computer room'),
  ('science_room','Laboratorio','Laboratori','Science room'),
  ('gym_1','Gimnasio','Gimnàs','Gym'),
  ('swing','Columpio','Gronxador','Swing'),
  ('slide','Tobogán','Tobogan','Slide'),
  ('door','Puerta','Porta','Door'),
  ('bus_single_decker','Autobús','Autobús','Bus'),
  ('car','Coche','Cotxe','Car'),
  ('wheelchair','Silla de ruedas','Cadira de rodes','Wheelchair'),
  ('surgery_health_centre','Centro de salud','Centre de salut','Health centre'),
  ('beach','Playa','Platja','Beach'),
 ],
 'juego': [
  ('ball','Pelota','Pilota','Ball'),
  ('bricks','Bloques','Blocs','Bricks'),
  ('lego','Piezas de construcción','Peces de construcció','Building blocks'),
  ('jigsaw_puzzle','Puzle','Trencaclosques','Jigsaw'),
  ('toys','Juguetes','Joguines','Toys'),
  ('bubbles','Pompas','Bombolles','Bubbles'),
  ('puppet','Marioneta','Titella','Puppet'),
  ('teddy_bear','Peluche','Ninot de peluix','Teddy bear'),
  ('doll','Muñeca','Nina','Doll'),
  ('toy_car','Coche de juguete','Cotxe de joguina','Toy car'),
  ('dinosaur','Dinosaurio','Dinosaure','Dinosaur'),
  ('playing_cards','Cartas','Cartes','Cards'),
  ('roll_dice_,_to','Tirar el dado','Tirar el dau','Roll the dice'),
  ('computer_game','Videojuego','Videojoc','Computer game'),
  ('musical_instruments','Instrumentos','Instruments','Instruments'),
  ('drum','Tambor','Tambor','Drum'),
  ('beanbag','Puf','Puf','Beanbag'),
  ('trampoline_,_to','Cama elástica','Llit elàstic','Trampoline'),
  ('childrens_tv','Dibujos animados','Dibuixos animats','Cartoons'),
 ],
 'tiempo': [
  ('morning','Por la mañana','Al matí','Morning'),
  ('afternoon','Por la tarde','A la tarda','Afternoon'),
  ('night','Noche','Nit','Night'),
  ('today','Hoy','Avui','Today'),
  ('tomorrow','Mañana','Demà','Tomorrow'),
  ('yesterday','Ayer','Ahir','Yesterday'),
  ('now','Ahora','Ara','Now'),
  ('first','Primero','Primer','First'),
  ('next','Siguiente','Següent','Next'),
  ('last','Último','Últim','Last'),
  ('before','Antes','Abans','Before'),
  ('after','Después','Després','After'),
  ('calendar','Calendario','Calendari','Calendar'),
  ('sun','Sol','Sol','Sun'),
  ('cloudy','Nublado','Ennuvolat','Cloudy'),
  ('rain','Lluvia','Pluja','Rain'),
  ('snow','Nieve','Neu','Snow'),
 ],
 'matematicas': [
  ('@sumar','Sumar','Sumar','Add'),
  ('subtract','Restar','Restar','Subtract'),
  ('multiply','Multiplicar','Multiplicar','Multiply'),
  ('divide','Dividir','Dividir','Divide'),
  ('same','Igual','Igual','Equal'),
  ('count_2_,_to','Números','Nombres','Numbers'),
  ('counters','Fichas para contar','Fitxes per comptar','Counters'),
  ('half','La mitad','La meitat','Half'),
  ('money','Dinero','Diners','Money'),
  ('square','Cuadrado','Quadrat','Square'),
  ('rectangle','Rectángulo','Rectangle','Rectangle'),
  ('triangle_equilateral','Triángulo','Triangle','Triangle'),
  ('circle','Círculo','Cercle','Circle'),
  ('oval','Óvalo','Oval','Oval'),
  ('pyramid_square_base','Pirámide','Piràmide','Pyramid'),
  ('shapes','Figuras','Figures','Shapes'),
  ('measuring_jug','Jarra medidora','Gerra mesuradora','Measuring jug'),
  ('scales','Báscula de cocina','Bàscula de cuina','Kitchen scales'),
  ('scales_2','Báscula','Bàscula','Scales'),
  ('graph_column','Gráfico de barras','Gràfic de barres','Bar chart'),
  ('pie_chart','Gráfico de sectores','Gràfic de sectors','Pie chart'),
  ('long','Largo','Llarg','Long'),
  ('short','Bajo','Baix','Short'),
  ('heavy','Pesado','Pesant','Heavy'),
  ('full','Lleno','Ple','Full'),
  ('empty','Vacío','Buit','Empty'),
  ('minute','Minuto','Minut','Minute'),
 ],
 'naturaleza': [
  ('dog','Perro','Gos','Dog'),
  ('cat','Gato','Gat','Cat'),
  ('bird','Pájaro','Ocell','Bird'),
  ('fish','Pez','Peix','Fish'),
  ('horse','Caballo','Cavall','Horse'),
  ('cow','Vaca','Vaca','Cow'),
  ('piglet','Cerdo','Porc','Pig'),
  ('sheep','Oveja','Ovella','Sheep'),
  ('rabbit','Conejo','Conill','Rabbit'),
  ('duck','Pato','Ànec','Duck'),
  ('frog','Rana','Granota','Frog'),
  ('butterfly','Mariposa','Papallona','Butterfly'),
  ('bee_bumble','Abeja','Abella','Bee'),
  ('lion','León','Lleó','Lion'),
  ('elephant','Elefante','Elefant','Elephant'),
  ('tree','Árbol','Arbre','Tree'),
  ('flower','Flor','Flor','Flower'),
  ('leaf','Hoja','Fulla','Leaf'),
  ('plant','Planta','Planta','Plant'),
  ('mountains','Montaña','Muntanya','Mountain'),
  ('Moon','Luna','Lluna','Moon'),
  ('star','Estrella','Estel','Star'),
  ('rainbow','Arcoíris','Arc de Sant Martí','Rainbow'),
 ],
 'cuerpo': [
  ('head','Cabeza','Cap','Head'),
  ('eyes','Ojos','Ulls','Eyes'),
  ('ear','Oreja','Orella','Ear'),
  ('mouth','Boca','Boca','Mouth'),
  ('teeth','Dientes','Dents','Teeth'),
  ('arm','Brazo','Braç','Arm'),
  ('leg','Pierna','Cama','Leg'),
  ('foot','Pie','Peu','Foot'),
  ('finger','Dedo','Dit','Finger'),
 ],
 'transporte': [
  ('train','Tren','Tren','Train'),
  ('boat','Barco','Vaixell','Boat'),
  ('bicycle','Bicicleta','Bicicleta','Bicycle'),
 ],
}
